### ISSUE TITLE
Feature Request: Add `col.dv`, `col.mdv`, and `col.amt` arguments to `NMcheckData()`

### ISSUE THREAD

**Issue by billdenney** [philipdelff/NMdata#31]
This is somewhat related to #30 (in that it's about column naming in `NMcheckData()`).

I like how `NMcheckData()` does not require the default column names as stated in #30, I often use names that are closer to the SDTM and ADaM source data names for easier tracking back to the origin.

With that, it appears that `NMcheckData()` has column renaming for many but not all columns that are checked.  The columns that do not appear to have the ability to use other names that I've found so far appear to be `col.dv`, `col.mdv`, and `col.amt`.  `col.evid` also doesn't appear to exist, but that doesn't seem like a name I'd use something different for.  (So, `col.evid` may be of interest for completeness, but it's not a real need to me.)

A simple workaround that I'm doing right now is simply renaming the columns as they go into `NMcheckData()` which is not a significant hardship.

**Comment by philipdelff** [comment]
I agree. NMdata must not require the user to name columns, files, or whatever in certain ways.

When I wrote NMcheckData I took some shortcuts and hard-coded some of the column names, and I haven't generalized all of them yet. However, in the master branch col.dv and col.mdv were already supported. I added support for col.amt just now. 

Having said that, there is still room for improvement. col.cmt support multiple column names (in case one data set is used for models with different numbers of compartments, it makes sense to include separate columns for that). We could also have multiple col.dv. In that case, col.dv and col.mdv would have to be matched too. Since this is beyond the scope of the request, I close this for now.
